DROP DATABASE IF EXISTS WEBSERVERDB;
CREATE DATABASE WEBSERVERDB CHARACTER SET utf8mb4;
USE WEBSERVERDB;
 
CREATE TABLE FILERECORD (
    CHECKSUM VARCHAR(190) NOT NULL PRIMARY KEY,
    DAY INT NOT NULL,
    DATECREATION DATE NOT NULL,
    PATH VARCHAR(255) NOT NULL
);
